### ISSUE TITLE
Develop SignUp API

### ISSUE THREAD

**Issue by davidrobinson05** [DRobinson4105/COP4331-Large-Project#18]
- Take in Username
- Take in Display Name
- Take in password and googleID, only adding the non-empty one
- Take in email
- If email is already used, return "Email linked to existing account" error.
- If user already exists, return "User already exists" error.
- Create a user in the database.
- 
- Return UserID.

- [ ] Setup API endpoint

**Comment by bouloutef04** [comment]
Done
