### ISSUE TITLE
Develop Get Profile API

### ISSUE THREAD

**Issue by davidrobinson05** [DRobinson4105/COP4331-Large-Project#20]
- [x] - Take in the UserID for profile.
- [ ] - 
- [x] - Return Username, Display Name, Profile Picture, About Me Description.
- [x] - If User does not exist, "Return User Does Not Exist" error.

**Comment by icblaze** [comment]
DONE

**Comment by icblaze** [comment]
It is done now.
- Made code
- Added (and passed) unit testing
- Added documentation to the yaml

**Comment by icblaze** [comment]
Updated it so it should have better tests and it should only give back the correct information
